feat: Implement the edit_message action
ZeLarpMaster/Mobius pull request #121
Opened 2021-10-24 19:40 UTC by Blond11516

Part of #29

- Adds the edit_message action.
- Adds the notion of "constraints" to endpoints. Constraints are like validations, except that they can look at multiple parameters at a time instead of only one. Useful for implementing "at least on of" or "only one of" type validations.
- Adds support for multipart messages to the generic rest module. It currently assumes a `:file` option. Looking at the discord docs, it looks like `create_message` and `edit_message` are the only two endpoints that use such an option.
- Documents the different available validations and constraints for actions
- Adds a step to the action executor to check that the bot is ready.
- In the `hanshake_shard` test setup, add a small delay before returning to make sure the shard has had time to receive and handle the message telling it it's ready. Also asserts that the bot is ready.
- Allow the `assert_has_error` test helper to receive only a single error instead of a list.

2021-10-25 02:03 UTC, ZeLarpMaster requested changes
Overall pretty good stuff, I like the way multipart is handled declaratively!

2021-10-25 02:03 UTC, ZeLarpMaster commented on lib/mobius/actions/message.ex
> +      constraints: [{:one_of, [:content, :embed, :file]}],
I think `:at_least_one_of` would be more appropriate since I'd expect an `:only_one_of` to happen later and it would cause confusion

2021-10-25 02:03 UTC, ZeLarpMaster commented on lib/mobius/actions/message.ex
> +      Edits an exsting message
Typo: `existing`

2021-10-25 02:03 UTC, ZeLarpMaster commented on lib/mobius/actions/message.ex
> +      Be awarae that updating flags works as a complete replacement. This means
Typo: `aware`

2021-10-25 02:03 UTC, ZeLarpMaster commented on lib/mobius/endpoint.ex
> +  - constraints: Additional contstraints for `:opts` that that involve
Typo: `contstraints` --> `constraints`

2021-10-25 02:03 UTC, ZeLarpMaster commented on lib/mobius/validations/action_validations.ex
> +  Contsraints are similar to validator in that they verify that some conditions
Typo: `Constraints`

2021-10-25 02:03 UTC, ZeLarpMaster commented on lib/mobius/validations/action_validations.ex
> +            |> Enum.join(", ")
TIL that `Enum.join` with a list of atoms still works

2021-10-25 02:03 UTC, ZeLarpMaster commented on test/support/fixtures.ex
> +    Process.sleep(5)
5ms is not a long time, but I guess we'll see if the tests are unstable

2021-10-25 02:42 UTC, Blond11516 commented on lib/mobius/actions/message.ex
> +      constraints: [{:one_of, [:content, :embed, :file]}],
Good point!

2021-10-25 02:45 UTC, Blond11516 commented on lib/mobius/validations/action_validations.ex
> +            |> Enum.join(", ")
Yeah I initially did the conversion manually but I tried it out of curiosity and it worked 😛 Looking at the docs, anything "convertible to a string" works.

2021-10-25 02:49 UTC, Blond11516 commented on test/support/fixtures.ex
> +    Process.sleep(5)
We really don't need a long delay here. I added it because I was getting one after some changes, but even with 1 ms I couldn't get a test to fail. I think that since there's basically nothing going on at that point just the fact that the process yields its thread is enough for the shard to pick up the message.

I bumped it up because I assumed the CI runners are slower than my machine, but I think it should work fine.

2021-11-01 22:04 UTC, ZeLarpMaster approved these changes

2021-11-02 01:47 UTC, merged