feat: Cogs
ZeLarpMaster/Mobius pull request #19
Opened 2020-12-30 22:36 UTC by Blond11516

TODO:
- [ ] Write documentation for the Cog module
- [ ] Add support for simple command handlers
- [ ] Add a cog loader to automatically load static cogs
- [ ] Add tests

2020-12-31 00:42 UTC, ZeLarpMaster reviewed
Overall that's a pretty good start and hypes me up because this means we're getting close to a v1 :tada:

2020-12-31 00:42 UTC, ZeLarpMaster commented on lib/mobius/services/cog.ex
> +      :persistent_term.put(:event_handlers, %{})
`:persistent_term` is global to all processes, so a key like `:event_handlers` without a namespace isn't exactly a best practice (see [the erlang docs](https://erlang.org/doc/man/persistent_term.html#best-practices-for-using-persistent-terms))

While you could namespace it, I don't really like the idea of using global state like this especially since anyone could shoot themselves in the foot by modifying it. I think it would be better to use [module attributes](https://hexdocs.pm/elixir/Module.html#register_attribute/3) instead to store the event handlers during compilation.

2020-12-31 00:42 UTC, ZeLarpMaster commented on lib/mobius/cogs/test_cog.ex
> +  use Mobius.Services.Cog
The module itself isn't exactly a service, but it also doesn't feel like core, or actions. So I feel like `Mobius.Cog` might be more appropriate?

2020-12-31 00:42 UTC, ZeLarpMaster commented on lib/mobius/services/cog.ex
> +      listen :message_create, %{"content" => content} do
That's such a good idea. I thought I'd split commands into a "command parsing service", but that's actually a much better idea since it puts the work on the cog process instead and doesn't involve a bunch of message passing to grab information from here and there. The only downside is it potentially duplicates some work, but honestly I don't think there's that much work happening in multiple places so it should be fine.

2020-12-31 00:42 UTC, ZeLarpMaster commented on lib/mobius/services/cog.ex
> +        {:ok, nil}
I wonder if we'll ever want an API to support the state here instead of always through ets tables :thinking: Definitely not for now or here, but it's a thought

2020-12-31 00:42 UTC, ZeLarpMaster commented on lib/mobius/services/cog.ex
> +      def handle_info({event_name, data}, state) do
Makes me wonder if we'd want a special key prefix to put in these messages so they don't collide with other messages. I realize a 2 element tuple is kinda generic and could easily happen with things like `{:ok, any}`.

2020-12-31 00:42 UTC, ZeLarpMaster commented on lib/mobius/services/cog.ex
> +          end
What does all this transformation of `contents` do? It looks to me like it only makes it always return `:ok`, but I'm not sure of why that's necessary

2020-12-31 00:42 UTC, ZeLarpMaster commented on lib/mobius/services/cog.ex
> +      :persistent_term.put(:event_handlers, %{})
Looking back at how it's used, I think you can replace this one with `Module.register_attribute/3`, the `:persistent_term.get` with `Module.get_attribute/3` and the persistent term update with `Module.put_attribute/3` and I feel like this should work :thinking:

2020-12-31 00:42 UTC, ZeLarpMaster commented on lib/mobius/services/cog.ex
> +      :persistent_term.put(:event_handlers, updated_handlers)
Doesn't this quote do too much? All of that code ends up executed in the module afterwards, but I feel like this could run inside the macro instead :thinking: I know it isn't leaking anything into the module, but it still feels weird.

2020-12-31 03:47 UTC, Blond11516 commented on lib/mobius/services/cog.ex
> +      :persistent_term.put(:event_handlers, %{})
I had tried to do it with module attributes at first but couldn't get it to work (ping me if you want to know the details). I've got it working now with `@before_compile`!

2020-12-31 03:48 UTC, Blond11516 commented on lib/mobius/cogs/test_cog.ex
> +  use Mobius.Services.Cog
Yeah I wasn't sure where to put it. `Mobius.Cog` feels good to me.

2020-12-31 03:50 UTC, Blond11516 commented on lib/mobius/services/cog.ex
> +      listen :message_create, %{"content" => content} do
Yeah the gist of command management can still be written in a dedicated module, but I think having the entrypoint here is going to be the simplest solution by far.

2020-12-31 03:52 UTC, Blond11516 commented on lib/mobius/services/cog.ex
> +      def handle_info({event_name, data}, state) do
That's a good point. Another solution would be to generate a bunch of different `handle_info` definitions to pattern match message separately. I don't think that would be too hard to do :thinking:

2020-12-31 03:53 UTC, Blond11516 commented on lib/mobius/services/cog.ex
> +        {:ok, nil}
Yeah I thought about that too. I feel like it would be a nice option to have, but off the top of my head I fail to see a use case where you'd want a state but wouldn't rather have it be persisted in an ETS...

2020-12-31 03:55 UTC, Blond11516 commented on lib/mobius/services/cog.ex
> +          end
TBH I'm not too sure, but `contents =` through `contents = Macro.escape(contents, unquote: true)` is copy-pasted from ExUnit, so I assume it's necessary? I'll do some testing to try and figure out exactly what this whole portion does.

2020-12-31 03:59 UTC, Blond11516 commented on lib/mobius/services/cog.ex
> +      :persistent_term.put(:event_handlers, updated_handlers)
I agree it's kind of heavy, but all all attribute manipulation has to happen inside the returned AST, so anything that manipulates the `event_handlers` has to be quoted.

2020-12-31 04:07 UTC, ZeLarpMaster commented on lib/mobius/services/cog.ex
> +        {:ok, nil}
There's definitely cases where we don't want persistance (like temporary caching or a state for tasks), but that'll come later

2020-12-31 04:26 UTC, ZeLarpMaster commented on lib/mobius/services/cog.ex
> +      def handle_info({event_name, data}, state) do
I think a special key prefix might be simpler and easier to read than some macro trickery to generate callbacks + it avoids unexpected behavior where a cog `send/2` itself a tuple, but doesn't receive the answer in its `handle_info`

That's also the way [GenServer distinguishes its `call` and `cast` from the other messages](https://github.com/erlang/otp/blob/master/lib/stdlib/src/gen_server.erl#L875)

2020-12-31 04:33 UTC, ZeLarpMaster commented on lib/mobius/services/cog.ex
> +          end
It might be how `test` supports the [implicit try](https://hexdocs.pm/elixir/Kernel.html#def/2-rescue-catch-after-else). My hypothesis on why they did all of that is they might've needed it just to add the `:ok`, but since we don't need any of it, we might be fine passing `contents` along directly as `def/2`'s 2nd argument (ie.: `def unquote(event_name)(unquote(var)), unquote(contents)`). This might be worth the try. If it doesn't work, I'd suggest either extracting this into a function with comments explaining its purpose or simply adding comments about the why.

2020-12-31 17:13 UTC, Blond11516 commented on lib/mobius/services/cog.ex
> +          end
You were right, I just removed the whole `case` and everything seems to be working fine.

2021-01-06 06:34 UTC, ZeLarpMaster requested changes
Whew! That's a lot of comments! Overall I really like where this is going, the architecture looks very good though I foresee a couple of changes in here in a decently far future, but it shouldn't be too bad. Obviously a lot of these comments are very nitpicky and this is a very important chunk of code, so I hope you won't feel too bad about this :P

2021-01-06 06:34 UTC, ZeLarpMaster commented on .formatter.exs
> +  # Mobius.Services.Cog
`Mobius.Cog` now

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +            Command.execute(command, arg_values)
I think this whole thing would be simpler if a single function in Command was doing all of that (`Command.parse_command/2`, `Command.execute/2`, and the argument error handling). The function could return `{:ok, return_value_of_the_command} | {:error, reason}`. It would reduce the amount of logic required in `Cog` which in my opinion is a win.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +              # credo:disable-for-next-line Credo.Check.Readability.StringSigils
I think it would be better to fix this instead of disabling it

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  have two ways of interacting with Discord: `listen/3` and `command/3`.
> Cogs have two ways of interacting with Discord

I see what you mean, but that's not technically right which might lead to confusion. Those are the two ways for the cog to bind itself to events. Cogs can interact with Discord through everything in `Mobius.Actions` which will eventually be more than 100 functions.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  interaction in Discord.
> These events are generally the result of normal user interaction in Discord.

While that's true, I think we can be a bit more specific. Maybe something along the lines of

> Events are sent when users (humans or bots) interact with Discord. These include almost everything you can do on Discord from messages sent to users changing their username. For a complete list of events and the data associated with them see the Events documentation page.

The Events documentation page doesn't exist yet, but I think it would be the best place to put all of that information instead of having it in a random module somewhere.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  textual chat to manually trigger an interaction with the bot.
Bots aren't necessarily in only one server so it would be more accurate to say something like the following. I also think it might be worth being a little bit more specific about the interaction with the bot.

> `command/3` defines a command which can be used by users in text channels where the bot has the permission to read. These commands will execute the code specified in the `do` block of the command with its arguments.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +      Logger.puts("Welcome \#{user["username"]}")
I don't think `Logger.puts/1` exists. I assume you changed it from `IO.puts` :P

Also the `\` before the `#` probably makes this line not compile. In general I think we need to be careful with code in user-visible docs because people will definitely copy paste stuff from the docs and it's likely to cause trouble if the code doesn't run.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +    "times" times
It would probably be even better if these explanations were directly inside the code snippet as comments. This way if people copy paste it, they'll grab the comments with it which would help them better understand exactly which parts do what.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  The second parameter, "payload", can be used to access the events payload.
Just like above, we could "link" to the Events page which includes all possible events even though it doesn't exist yet.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +      existing_handlers = Module.get_attribute(__MODULE__, :event_handlers)
Out of curiosity, can you use the `@` notation here or does it not work? I feel like `@event_handlers` would be easier to read here than all of this, but I'm not sure whether that's actually possible or not 🤔

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +      existing_handlers = Module.get_attribute(__MODULE__, :event_handlers)
The `put_attribute` would become `@event_handlers {event_name, Function.capture(__MODULE__, name, 1)}`

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  spaces).
You don't have to do it in this PR, but it would be very nice if we could `raise` an exception in the macro if this requirement isn't met such that it fails at compile time which makes it very easy to debug.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  oh the command body.
typo
> as part __oh__ the command body

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  compilation warning indicating that the second command will be ignored.
I think this should be a compilation error. Two commands with the same name on different cogs could be a warning (to be implemented later), but two in the same cog is likely a programmer error (copy pasting stuff and forgetting to change the name of the command) and treating it as such makes it easier to debug than a warning which might be missed during compilation.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  command "add", num1: :integer, num2: integer do
typo, missing a `:` before the 2nd `integer` type

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  myBot: "Invalid type for argument "num2". Expected "integer", got "hello".
While it might not be the term used colloquially, I think it's better to use technical terms like `In a Discord text channel` so people reading this can connect the dots between the concepts easily.

Also I think it's a typo, but the `"` before `Invalid type` should probably be removed (since it isn't closed at the end and wouldn't be in the message sent)

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +      handler: Function.capture(__CALLER__.module, handler_name, length(args))
I wonder if it would change anything if the `handler` was an anonymous function instead of a named and `def`'d function. It would definitely prevent all possible function name collisions, but maybe it silences compilation errors and stuff like that? This is just a thought though, probably not worth changing this.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +        )
Is the warning [in the docs](https://hexdocs.pm/elixir/IO.html#warn/1) relevant here? Since it's a macro I think maybe not, but I'm really not sure.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +      |> length()
Would `Enum.count(event_handles, & elem(&1, 0) == event_name)` work here?

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +    :"mobius_event_#{Atom.to_string(event_name)}_#{Integer.to_string(handler_id)}"
I don't think you need to convert the types before interpolating them:
```elixir
iex> :"something_#{:hello}_#{1}"
:something_hello_1
```

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/cogs/ping_pong.ex
> +  command "ping", do: Logger.info("pong")
I love this cog 😂

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/core/command.ex
> +  alias Mobius.Command.ArgumentParser
The module should probably be at `Mobius.Core.Command.ArgumentParser` or even `Mobius.Core.ArgumentParser` instead

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/core/command.ex
> +  @spec get_command_arg_names(keyword(atom())) :: [atom()]
Isn't the type here `keyword(ArgumentParser.arg_type())` instead of `keyword(atom())`? I know it's a long type, but you could probably define it at the top as `@type args :: keyword(ArgumentParser.arg_type())`

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/core/command.ex
> +          | {:invalid_args, [{Validator.arg_type(), String.t()}]}
Since this return type could possibly be useful elsewhere (and also because it's very long), I think it would be better if it was defined at the top so it could be used in other modules without copy pasting all of this.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/core/command.ex
> +         end) do
Would probably be slightly more readable by splitting this line with pipes:
```elixir
commands
|> Enum.find(fn ... end)
|> case do
```

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/core/command.ex
> +          |> String.split()
It's not the case yet, but the parsing logic will eventually be smarter than just splitting on spaces, so it would be nice (not necessary) if this could be either inside `validate` or going through another function dedicated to parsing the argument strings.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/core/command.ex
> +          {:ok, [any()]} | {:too_few_args, t(), non_neg_integer()} | {:invalid_args, [String.t()]}
I don't remember why or what exactly (was it the compiler or ElixirLS?), but I know something was complaining about specs on private functions. I should look into it, but you can pretty much remove the spec here.

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/core/command/argument_parser/integer.ex
> +      {int, _} -> int
This will return `5` for the value `"5.0"` which is not exactly what we want. It can be fixed with:

```suggestion
      {int, ""} -> int
      _ -> :error
```

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/services/cog_loader.ex
> +  @spec load_cog(module()) :: DynamicSupervisor.on_start_child()
I'm assuming it was forgotten while refactoring, but `load_cog/1` actually returns `:ok`

2021-01-06 06:34 UTC, ZeLarpMaster commented on lib/mobius/services/cog_loader.ex
> +    {:ok, @initial_cogs}
Do you think this service could ever have more than the list of cogs in its state? I feel like we should future-proof it and wrap the list in a simple map 🤔

2021-01-07 01:25 UTC, Blond11516 commented on lib/mobius/cog.ex
> +              # credo:disable-for-next-line Credo.Check.Readability.StringSigils
Right, at first I thought you couldn't use interpolation in the string sigil but I had forgotten about the lowercase version. Will fix!

2021-01-07 01:31 UTC, Blond11516 commented on lib/mobius/cog.ex
> +  interaction in Discord.
Another option for the Event documentation (and all kinds of general documentation) would be a "Guides" section in the docs, like Phoenix does for example.

I think this would be an interesting option because I don't think we intend for the `Events` module to be "public", right?

2021-01-07 01:40 UTC, Blond11516 commented on lib/mobius/cog.ex
> +      Logger.puts("Welcome \#{user["username"]}")
Yup, I wanted to write `IO` :stuck_out_tongue: 

I just generated the docs and `\#{user["username"]}` does get escaped properly to `#{user["username"]}`, but wrapping the doc in `~S` and getting rid of the `\` looks nicer anyway.

2021-01-07 01:47 UTC, Blond11516 commented on lib/mobius/cog.ex
> +      existing_handlers = Module.get_attribute(__MODULE__, :event_handlers)
I get a warning saying the attribute is undefined and then an error because something is `nil`. I never saw the `@attribute` syntax in any macro example I looked at, so I'm pretty sure it's just not allowed.

2021-01-07 01:48 UTC, Blond11516 commented on lib/mobius/cog.ex
> +  spaces).
Good point. I'll add a todo.

2021-01-07 01:49 UTC, Blond11516 commented on lib/mobius/cog.ex
> +  compilation warning indicating that the second command will be ignored.
Is it even worth documenting this then?

2021-01-07 01:59 UTC, Blond11516 commented on lib/mobius/cog.ex
> +      handler: Function.capture(__CALLER__.module, handler_name, length(args))
Hmm that's an interesting point. I had originally went with named functions since I was using `apply/3` to call them (which uses the module and function name rather than the function itself), but it would indeed make the code simpler if we could use anonymous functions (since we could remove the counts and stuff). I'll look into this, I think it's worth it.

2021-01-07 02:02 UTC, Blond11516 commented on lib/mobius/cog.ex
> +        )
The warning is for `warn/1`, not `warn/2`.

Also per your previous comment I changed it to an error so it doesn't matter either way :stuck_out_tongue:

2021-01-07 02:05 UTC, Blond11516 commented on lib/mobius/cog.ex
> +      |> length()
Looks like it works!

2021-01-07 02:06 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  interaction in Discord.
Everything outside `Mobius.Actions` (and `Mobius.Cog` now I guess :P) won't be public indeed. I also wanted the Events page to be in a "Guides" section so we were on the same page about that!

2021-01-07 02:07 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +      existing_handlers = Module.get_attribute(__MODULE__, :event_handlers)
Good to know! Thanks

2021-01-07 02:07 UTC, Blond11516 commented on lib/mobius/cogs/ping_pong.ex
> +  command "ping", do: Logger.info("pong")
Haha thanks! :stuck_out_tongue: 

I removed my `TestCog` but I thought we could keep this as a sanity check, kind of like people often do with APIs.

2021-01-07 02:09 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  compilation warning indicating that the second command will be ignored.
Probably not, you're right

2021-01-07 02:10 UTC, Blond11516 commented on lib/mobius/core/command.ex
> +  alias Mobius.Command.ArgumentParser
Good point. Which do you prefer? The module names are getting kind of long for the implementation modules, but I feel like it really makes more sense under `Command` :thinking:

2021-01-07 02:12 UTC, Blond11516 commented on lib/mobius/core/command.ex
> +  @spec get_command_arg_names(keyword(atom())) :: [atom()]
I don't really mind the long spec, it's not like short specs aren't common anyway :stuck_out_tongue:

2021-01-07 02:19 UTC, ZeLarpMaster commented on lib/mobius/core/command.ex
> +  alias Mobius.Command.ArgumentParser
I agree the names get long, but it usually only makes the alias longer so it shouldn't matter much. I prefer keeping Core flat if possible, but I'm also starting to think `Mobius.Core.Command` will likely have more modules as features are added so maybe it's better to keep them together 🤔 So keeping it under Command sounds better

2021-01-08 02:51 UTC, Blond11516 commented on lib/mobius/core/command.ex
> +          |> String.split()
I put it in a separate function. More functions = more better ;)

2021-01-08 02:52 UTC, Blond11516 commented on lib/mobius/core/command.ex
> +          {:ok, [any()]} | {:too_few_args, t(), non_neg_integer()} | {:invalid_args, [String.t()]}
Would be nice if you could find what it was, I don't remember ever seeing an issue with that :thinking:

2021-01-08 02:53 UTC, Blond11516 commented on lib/mobius/core/command/argument_parser/integer.ex
> +      {int, _} -> int
Good catch!

2021-01-08 02:55 UTC, Blond11516 commented on lib/mobius/services/cog_loader.ex
> +  @spec load_cog(module()) :: DynamicSupervisor.on_start_child()
This is indeed a refactoring error, but I wasn't sure what we wanted it to return. Is `:ok` good? Could we gain something from actually returning `on_start_child()`?

2021-01-08 02:56 UTC, Blond11516 commented on lib/mobius/services/cog_loader.ex
> +    {:ok, @initial_cogs}
Sure, don't see why not

2021-01-08 02:58 UTC, Blond11516 commented on lib/mobius/cog.ex
> +  have two ways of interacting with Discord: `listen/3` and `command/3`.
I updated this part. Let me know what you think.

2021-01-08 03:19 UTC, ZeLarpMaster commented on lib/mobius/services/cog_loader.ex
> +  @spec load_cog(module()) :: DynamicSupervisor.on_start_child()
I think `:ok` is fine, the pid shouldn't ever be used directly since it might change if the cog restarts so that leaves us with the `:ok` or an error.

2021-01-08 03:30 UTC, ZeLarpMaster commented on lib/mobius/core/command.ex
> +          {:ok, [any()]} | {:too_few_args, t(), non_neg_integer()} | {:invalid_args, [String.t()]}
I looked at ElixirLS, dialyzer, credo, and compilation. None of them seem to say anything about it so I think I was confusing it with `@doc`:
![image](https://user-images.githubusercontent.com/1305105/103970650-c3cce100-5136-11eb-88a0-25823ccb9c89.png)

I consider `@spec`s to be documentation for the user of the function, but for private functions, we can't document the functions, so I probably never put any specs because of that. So far none of the private functions have a spec, so I don't know if we want to start writing specs everywhere starting now or continue not writing specs. I feel like you need to read private functions to know what they do anyway, so the specs don't add much value at the cost of bloating code a little bit (especially for functions which are one-liners) and I'd much prefer a hard, always followed, rule than an arbitrary "if function is big enough, put a spec"

This is up for debate and this PR is probably not the right place for such a debate. You can do whichever you want and we can talk about it on Discord

2021-01-08 03:35 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  have two ways of interacting with Discord: `listen/3` and `command/3`.
Looks good!

2021-01-12 01:32 UTC, Blond11516 commented on lib/mobius/cog.ex
> +            Command.execute(command, arg_values)
I've moved what I could to the `Command` module, but there really wasn't a lot of logic in that case statement anyway. Let me know what you think.

2021-01-12 01:33 UTC, Blond11516 commented on lib/mobius/core/command.ex
> +          {:ok, [any()]} | {:too_few_args, t(), non_neg_integer()} | {:invalid_args, [String.t()]}
I removed the specs for private functions, I really don't have any strong feelings about this.

2021-01-12 02:15 UTC, Blond11516 commented on lib/mobius/cog.ex
> +      handler: Function.capture(__CALLER__.module, handler_name, length(args))
Well, I can't get it to work, nor can I find any examples of this, so I'm gonna drop this for now.

2021-01-12 03:55 UTC, ZeLarpMaster reviewed
Great work! Some stuff will eventually be moved around to support other features, but for now this looks very good!

2021-01-12 03:55 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +    # Every time a user enters "repeat word times", repeatthe word "word"
Typo: missing a space between "repeat" and "the"

2021-01-12 03:55 UTC, ZeLarpMaster commented on lib/mobius/services/cog_loader.ex
> +      {:ok, _pid, _info} -> {:reply, :ok, %{state | cogs: [cog | state.cogs]}}
We're actually in control of what `Cog` returns on `init/2` so we know it's impossible for cogs to reply with `{:ok, _pid, _info}`. I'm not sure if this was added because of linters, but unless that's the case, I think you can remove this line.

2021-01-16 23:59 UTC, ZeLarpMaster requested changes
A few typos to be fixed, but overall looks very good! After those fixes it will be good to merge

2021-01-16 23:59 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +      end
Out of curiosity, what happens if the cog defines its own `handle_info`? Does it use the cog's before the generated one or the other way around? I think that might be worth documenting at the very least.

2021-01-16 23:59 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +  The second parameter defires the list of arguments that the command accepts,
Typo: `defires` --> `defines`

2021-01-16 23:59 UTC, ZeLarpMaster commented on lib/mobius/cog.ex
> +              "Command \"#{command.name}\" already exists. Duplicated command will be ignored."
`Duplicated command will be ignored.` Well technically it makes a compilation error so it isn't exactly ignored :P

2021-01-16 23:59 UTC, ZeLarpMaster commented on lib/mobius/core/command.ex
> +          | {:invalid_args, [{{:atom, ArgumentParser.arg_type()}, String.t()}]}
`:atom` means the literal atom `:atom`, I think this is a typo for `atom()` 🤔

2021-01-16 23:59 UTC, ZeLarpMaster commented on lib/mobius/core/command.ex
> +        with {:ok, values} <- validate(command, arg_values) do
I think we could merge `validate` and `execute` here and it would make this module a bit simpler. It would look like this:
```elixir
def execute_command(commands, message) do
  # the rest of parse_command
  with :ok <- validate_arg_count(command, values),
          {:ok, values} <- parse_arg_values(command, values) do
    {:ok, apply(command.handler, values)}
  end
```
And `handle_message`'s body becomes only `execute_command(commands, message)`

This removes 2 privates functions by inlining them and makes the flow a bit easier to follow. What do you think?

2021-01-16 23:59 UTC, ZeLarpMaster commented on test/mobius/core/command_test.exs
> +      {:ok, command: command}
Can also do `[command: command]` btw

2021-01-16 23:59 UTC, ZeLarpMaster commented on test/support/cog_stub.ex
> +    |> Process.whereis()
`send` can receive the name of a locally registered process so you don't need to do `Process.whereis`

2021-01-17 14:15 UTC, Blond11516 commented on lib/mobius/cog.ex
> +      end
The Cog's `handle_info` is defined first from the macro expansion, so as long as the message matches the declaration, it handles it. I'll document this.

2021-01-17 14:40 UTC, Blond11516 commented on lib/mobius/core/command.ex
> +        with {:ok, values} <- validate(command, arg_values) do
I agree with you, looking at the diff it does clean up the module nicely!

2021-01-17 14:40 UTC, Blond11516 commented on lib/mobius/cog.ex
> +      end
I added some doc about this. Let me know what you think!

2021-01-17 19:14 UTC, ZeLarpMaster submitted a review, later dismissed

2021-01-17 19:14 UTC, ZeLarpMaster commented on mix.lock
> +  "nimble_parsec": {:hex, :nimble_parsec, "1.1.0", "3a6fca1550363552e54c216debb6a9e95bd8d32348938e13de5eda962c0d7f89", [:mix], [], "hexpm", "08eb32d66b706e913ff748f11694b17981c0b04a33ef470e33e11b3d3a
I guess this sneaked in :P

2021-01-17 22:30 UTC, ZeLarpMaster approved these changes, later dismissed

2021-01-17 22:33 UTC, ZeLarpMaster approved these changes

2021-01-17 22:36 UTC, Blond11516 commented
@all-contributors pleas add @Blond11516 for code, tests and documentation

2021-01-17 22:36 UTC, merged