feat: Add "Create Reaction" action
ZeLarpMaster/Mobius pull request #69
Opened 2021-03-10 02:43 UTC by Blond11516

Adds the `create_reaction` action.

This PR is a part of https://github.com/ZeLarpMaster/Mobius/issues/29.

2021-03-10 02:44 UTC, Blond11516 commented on lib/mobius/actions/reaction.ex
> +  Add a reaction to a message with a custom emoji
The doc on both heads is really thin but I feel like the argument names and spec are pretty self-explanatory :shrug:

2021-03-10 03:18 UTC, ZeLarpMaster requested changes
Good work, I'm happy to see you picked a very important one as your first one 😄

My comments are pretty debatable so if you disagree with something, let me know

2021-03-10 03:18 UTC, ZeLarpMaster commented on lib/mobius/actions/reaction.ex
> +  def create_reaction(channel_id, message_id, custom_emoji_name, custom_emoji_id) do
I have a few suggestions on this API which may or may not be good ideas:
- I think using `Mobius.Models.Emoji.t()` instead of the name and id would be better since it would allow taking emojis from other endpoints or events and send them directly to this call. It would also merge both functions into a single function which makes it easier to take an emoji variable (regardless of whether it's custom or not) and send it to this function (instead of having to do a `if custom emoji, do: create_reaction/4, else: create_reaction/3` everytime). And finally it allows for:
- Putting the emoji as the first argument to make it easier to pipe the emoji from a config or an event into this function. I think you're more likely to grab the emoji from a few other function calls than the channel or message

2021-03-10 03:18 UTC, ZeLarpMaster commented on lib/mobius/rest/client.ex
> +  @type empty_result :: :ok | error()
Could replace `check_empty_response`'s return type to this

2021-03-10 03:18 UTC, ZeLarpMaster commented on lib/mobius/rest/reaction.ex
> +    |> Client.parse_response(fn _ -> :ok end)
I think this should be `Client.check_empty_response/1`

2021-03-10 03:18 UTC, ZeLarpMaster commented on test/mobius/actions/reaction_test.exs
> +      emoji_name = "party-parrot"
funnily enough this is an invalid custom emoji name ("can only contain alphanumeric characters and underscores"), though I guess it doesn't matter at all here

2021-03-10 03:18 UTC, ZeLarpMaster commented on lib/mobius/actions/reaction.ex
> +  Add a reaction to a message with a custom emoji
I agree, if more explanation is needed this can be changed in the future

2021-03-10 03:18 UTC, ZeLarpMaster commented on lib/mobius/actions/reaction.ex
> +  alias Mobius.Rest
I'd still add a `@moduledoc` here even if it's pretty simple just as a header for the docs which will eventually be on hexdocs

2021-03-14 14:50 UTC, Blond11516 commented on lib/mobius/rest/reaction.ex
> +    |> Client.parse_response(fn _ -> :ok end)
Didn't know this function exists, I'll change it.

2021-03-14 23:56 UTC, ZeLarpMaster requested changes
Almost there, just a little thing which is unclear in the docs. After that I think it's gonna be good to go 👍

2021-03-14 23:56 UTC, ZeLarpMaster commented on lib/mobius/actions/reaction.ex
> +  end
I like the idea of this function, it might be useful in `Mobius.Models.Emoji` since I'd guess it will be useful elsewhere.

There's a little problem though, `managed` actually means managed by a 3rd party. It's used for things like emotes from Twitch on servers binded to Twitch accounts. It's a little weird so if this doesn't make much sense, do tell me.

Instead I think this function can simply be (though it could be formatted differently)
```elixir
defp get_emoji_string(%Emoji{id: nil, name: name}), do: name
defp get_emoji_string(%Emoji{id: id, name: name}), do: "#{name}:#{id}"
```
This would match what other libs do (for example [discord.py](https://github.com/Rapptz/discord.py/blob/7836046621d6b670730217ad4de321ef3ecd5cff/discord/partial_emoji.py#L134))

2021-03-16 02:06 UTC, Blond11516 commented on lib/mobius/actions/reaction.ex
> +  end
Yeah, I really wasn't sure if there was a way to tell whether an emoji is custom or not since the doc apparently makes no mention of this whatsoever. Not sure where I got the idea that "managed" means "custom" though :thinking:

2021-03-16 02:46 UTC, ZeLarpMaster approved these changes, later dismissed
I'm fine with you merging this as is, but I'd also prefer if you made these tiny changes 😄

2021-03-16 02:46 UTC, ZeLarpMaster commented on lib/mobius/actions/reaction.ex
> +          Client.empty_result() | {:error, String.t()}
`{:error, String.t()}` is included in `Client.empty_result()`

2021-03-16 02:46 UTC, ZeLarpMaster commented on lib/mobius/actions/reaction.ex
> +      iex> emoji = %Mobius.Models.Emoji{name: "👌", require_colons: false, managed: false, animated: false, available: true}
I don't think you need to specify all the fields in here, it should be enough to only specify `name:`

2021-03-16 02:46 UTC, ZeLarpMaster commented on lib/mobius/models/emoji.ex
> +      iex> emoji = %Mobius.Models.Emoji{id: 123456, name: "👌", require_colons: false, managed: false, animated: false, available: true}
Same thing here

2021-03-16 02:55 UTC, ZeLarpMaster approved these changes
Good to go!

2021-03-16 02:56 UTC, merged