feat: Added Help cog and tracking cog docs and command docs
ZeLarpMaster/Mobius pull request #78
Opened 2021-04-07 03:22 UTC by ZeLarpMaster

Added the `Help` cog which supports:
- `[p]help`
- `[p]help <cog>`
- `[p]help <command>`

Closes #76

2021-05-23 14:57 UTC, Blond11516 requested changes

2021-05-23 14:57 UTC, Blond11516 commented on lib/mobius/cog_utils.ex
> +      "Cat1:\n  abc       description\n  defghi    something"
```suggestion
      ~S"
      Cat1:
        abc       description
        defghi    something
      "
      |> String.trim()
```
What do you think of that? It's definitely more verbose, but I think it's much more clear as to how the input gets formatted exactly.

2021-05-23 14:57 UTC, Blond11516 commented on lib/mobius/cog_utils.ex
> +      "Cat1:\n  abc       description\nCat2:\n  defghi    something"
```suggestion
      ~S"
      Cat1:
        abc       description
      Cat2:
        defghi    something
      "
      |> String.trim()
```

2021-05-23 14:57 UTC, Blond11516 commented on lib/mobius/cog_utils.ex
> +      "Cat1:\n  empty category"
```suggestion
      ~S"
      Cat1:
        empty category
      "
      |> String.trim()
```

2021-05-23 14:57 UTC, Blond11516 commented on lib/mobius/cog_utils.ex
> +  @type categories :: [{String.t(), [{String.t(), String.t()}]}]
That's a little dense. I think it would be worth it to extract parts of this to named types. What would you think of
```elixir
@type category_entry :: {String.t(), String.t()}
@type category :: {String.t(), [category_entry()]}
@type categories :: [category()] # Might not event be necessary, could easily be moved to the function spec
```

2021-05-23 14:57 UTC, Blond11516 commented on lib/mobius/cogs/help.ex
> +    |> reply()
What would you think of an "inverse with" like we did the other day?
```elixir
with nil <- try_cog(cog_or_command_name, cogs),
     nil <- try_command(cog_or_command_name, cogs) do
  {:reply, %{content: @not_found}}
else
  content -> {:reply, %{content: content, allowed_mentions: %{parse: []}}}
end
```
This probably is the opposite of idiomatic, but it feels a little weird to me that `try_command` has to worry about the fact that there might already be a result available...

2021-05-23 14:57 UTC, Blond11516 commented on lib/mobius/cogs/help.ex
> +  defp list_cog_commands(%Cog{commands: commands}) do
Shouldn't that be a concern of the Cog module?

2021-05-23 14:57 UTC, Blond11516 commented on lib/mobius/cogs/help.ex
> +  defp format_specific_cog(%Cog{} = cog) do
For the formatting functions, what would you think of "format_x"/"format_x_list" instead of "format_specific_x"/"format_xs"?

2021-05-23 14:57 UTC, Blond11516 commented on lib/mobius/cogs/help.ex
> +    "#{cog.description}\n```#{command_list}```#{@cog_footer}"
```suggestion
    formatted_commands = CogUtils.format_categories_list([{"Commands", commands}])

    "#{cog.description}\n```#{formatted_commands}```#{@cog_footer}"
```
I feel like "list" could be misleading here

2021-05-23 14:57 UTC, Blond11516 commented on lib/mobius/cogs/help.ex
> +  defp format_specific_cog(%Cog{} = cog) do
Right now it's pretty hard to get a sense of what the formatting functions' output is actually supposed to look like. I think it would be worth it to extract them to a `HelpFormatter` module and add doc(test)s to them, just to give concrete examples. I wouldn't add any additional unit tests though.

2021-05-23 14:57 UTC, Blond11516 commented on test/support/cog_test_utils.ex
> +  @doc "Asserts that a message was sent returns the body of the request"
```suggestion
  @doc "Asserts that a message was sent and returns the body of the request"
```
The end isn't quite true, the body isn't returned, but merely matched against the expectation. I think that just saying "and matches the body of the request against the expectation" might not be clear enough even though it's technically more accurate. What do you think?

2021-05-23 22:55 UTC, ZeLarpMaster commented on lib/mobius/cog_utils.ex
> +      "Cat1:\n  abc       description\n  defghi    something"
It messes with the spacing on the 2nd and 3rd lines though. I don't think there's a quick and easy way to make it work. Also, is the expected value executed? I thought it had to be matching what's printed or something like that 🤔 I'll try to make it better, but I'm a bit skeptical

2021-05-23 23:01 UTC, ZeLarpMaster commented on lib/mobius/cog_utils.ex
> +  @type categories :: [{String.t(), [{String.t(), String.t()}]}]
Oh you're absolutely right

2021-05-23 23:02 UTC, ZeLarpMaster commented on lib/mobius/cogs/help.ex
> +    |> reply()
Yeah it's probably opposite of idiomatic, but I don't really mind. imo it still reads better than the other options

2021-05-23 23:05 UTC, ZeLarpMaster commented on lib/mobius/cogs/help.ex
> +  defp list_cog_commands(%Cog{commands: commands}) do
I don't think so, the function actually goes in and generates tuples of `{command_name, description}` which I think is very specific to what's going on here. If there's a need for something very similar elsewhere, maybe we can put it together, but right now I really feel like this is specific enough to warrant being here

2021-05-23 23:05 UTC, ZeLarpMaster commented on lib/mobius/cogs/help.ex
> +  defp format_specific_cog(%Cog{} = cog) do
Sure, I agree it would be more readable 👍

2021-05-23 23:06 UTC, ZeLarpMaster commented on lib/mobius/cogs/help.ex
> +  defp format_specific_cog(%Cog{} = cog) do
Sounds good! It will also help with extracting it into a behavior for a future where we wanna output the help into an Embed instead of directly in the message.

2021-05-23 23:12 UTC, ZeLarpMaster commented on test/support/cog_test_utils.ex
> +  @doc "Asserts that a message was sent returns the body of the request"
Yeah I changed what this function does like 4 times while doing this PR and probably forgot to update the doc at some point 😅

It does however return the body of the request because the `assert unquote(x) = body` is the last thing in the quote which means `body = assert_message_sent(%{})` does in fact have the body of the request in the variable `body`. It's not really the expected way to use this macro though, I agree.

I think something like "Asserts and matches on the body of a message send request" with an example might be good enough? I don't really see how to be clear and concise here so I'd embrace it by providing examples instead.

2021-05-24 14:32 UTC, Blond11516 commented on lib/mobius/cog_utils.ex
> +      "Cat1:\n  abc       description\n  defghi    something"
Did you test it? It works as expected for me.

![image](https://user-images.githubusercontent.com/44734484/119362816-1ee11980-bc7b-11eb-8f24-3400cecad773.png)
![image](https://user-images.githubusercontent.com/44734484/119362914-3ae4bb00-bc7b-11eb-8231-5693ce9440fc.png)
![image](https://user-images.githubusercontent.com/44734484/119363002-551e9900-bc7b-11eb-8f5a-284b62d3e27c.png)

2021-05-24 14:44 UTC, Blond11516 commented on test/support/cog_test_utils.ex
> +  @doc "Asserts that a message was sent returns the body of the request"
You're right, I forgot `assert` actually returns the result! And I agree, examples are probably the way to go here.

2021-05-24 14:49 UTC, Blond11516 commented on lib/mobius/cogs/help.ex
> +    |> Enum.min_by(&elem(&1, 0))
`list_cog_commands` and `find_command_description` use `elem/2` a total of 3 times. This means that unless I have a very good understanding of how the command struct is built, it's pretty hard to know what's going on here. I think changing the `elem` calls to anonymous functions with explicit pattern matching would go a long way to make this clearer.

2021-05-24 14:51 UTC, Blond11516 commented on lib/mobius/cogs/help.ex
> +  defp list_cog_commands(%Cog{commands: commands}) do
There is an element of "tell don't ask" here though. This came to mind while writing my comment about `elem`, but should the help cog really be bothered so much with the internals of a cog? Maybe the function needs to be reworked a bit (ideally I'd see it returning `[%Command.t()]`) because I agree the exact use case here is pretty specific to the help command.

2021-05-30 01:36 UTC, ZeLarpMaster commented on lib/mobius/cog_utils.ex
> +      "Cat1:\n  abc       description\n  defghi    something"
I'm so confused by how this works. I'm expecting 6 spaces before "Cat1" in your screenshots and I don't get why that's not the case. I agree it's much better, I didn't know it worked like that. Thank you!

2021-05-30 02:08 UTC, ZeLarpMaster commented on lib/mobius/cogs/help.ex
> +  defp list_cog_commands(%Cog{commands: commands}) do
If you have a specific suggestion, I'm open to changing how it works, but I fail to see how we could make `Cog` return anything different and still useful here. The help command needs to list the commands of each cog together and then the description of each command (and sort all of that alphabetically). If we return `[%Command.t()]` from a function in Cog, we're doing work to flatten the structure, and then we're doing the exact opposite work to group the commands of each cog and then group the clauses of each command.

Maybe I'm just getting your comment wrong, in which case I apologize.

2021-05-30 14:15 UTC, Blond11516 commented on lib/mobius/cog_utils.ex
> +      "Cat1:\n  abc       description\n  defghi    something"
I guess the doctest algorithm accounts for that and "aligns" the sigil with the `iex>` prompt 🤷

2021-05-30 14:25 UTC, Blond11516 commented on lib/mobius/cogs/help.ex
> +  defp list_cog_commands(%Cog{commands: commands}) do
When you say we'd be doing work to flatten the structure and then regroup it are you thinking that "the function that would live inside the Cog module" (copyright pending) would return the list of _all_ commands? Cuz that's not what I had in mind.

I was just thinking that we could move this whole function to `Cog` in either one of two ways:
1. Move it as-is and maybe rename it to something like `get_sorted_command_descriptions`
2. Split and move it to something like `get_sorted_commands` and `get_command_description`. `Help` would then do something like `cog |> Cog.get_sorted_commands() |> Enum.map(&Cog.get_command_description/1)`

(Not sure how the second options would actually end up looking like, so the first might be better)

Again, for me this really boils down to "tell don't ask". The help command is doing a lot of work with the _internal_ representation of the cogs and commands, and I don't think it should have to.

2021-05-30 14:26 UTC, Blond11516 commented on lib/mobius/cogs/help.ex
> +  defp list_cog_commands(%Cog{commands: commands}) do
Maybe we need to talk about this over voice. Let me know if you want to do that!

2021-06-03 00:52 UTC, Blond11516 commented on lib/mobius/core/command.ex
> +  with the lowest arity
```suggestion
  with the lowest arity.
```

2021-06-03 00:52 UTC, Blond11516 submitted a review, later dismissed

2021-06-03 00:54 UTC, Blond11516 approved these changes

2021-06-03 00:55 UTC, merged