feat(actions): Implement edit channel action
ZeLarpMaster/Mobius pull request #90
Opened 2021-04-18 21:18 UTC by Blond11516

Implements the `edit_channel` action. Also adds some utility functions for validating action parameters.

This PR is part of #29.

2021-04-19 01:03 UTC, ZeLarpMaster requested changes

2021-04-19 01:03 UTC, ZeLarpMaster commented on lib/mobius/actions/channel.ex
> +  @spec edit_channel(pos_integer, edit_channel_body()) :: Client.result(Channel.t())
channel_id's type should be `Snowflake.t()`

2021-04-19 01:03 UTC, ZeLarpMaster commented on lib/mobius/actions/utils.ex
> +        string_length = String.length(value)
I wonder if Discord counts graphemes or codepoints. It would do a difference if, for example, there's emojis or multi-codepoint characters in channel names

2021-04-19 01:03 UTC, ZeLarpMaster commented on test/mobius/actions/utils_test.exs
> +    test "validator returns an error when provided a non-string input", ctx do
saying `validator` is a bit redundant with the describe; applies to all tests in this file

2021-04-19 01:03 UTC, ZeLarpMaster commented on test/support/fixtures.ex
> +      |> List.to_string()
Wouldn't it be simpler to just hardcode `"abcdefghijklmnopqrstuvwxyz"`?

2021-04-19 01:03 UTC, ZeLarpMaster commented on lib/mobius/actions/utils.ex
> +defmodule Mobius.Actions.Utils do
While this is indeed useful, that's kind of the point of the `Mobius.Validation` modules. So I think you could just move this in there

2021-04-20 00:00 UTC, Blond11516 commented on lib/mobius/actions/utils.ex
> +        string_length = String.length(value)
Just did a few tests. The API seems to count graphemes (generate 1024 characters, replaced 1 with an emoji and it worked, the client event displayed it properly), but if you try to do it from the client, it converts them to their textual representation (ie. `:thinking:`), which takes up more characters.

Given those results, using `String.length` appears to be the correct way here.

2021-04-20 00:03 UTC, Blond11516 commented on test/support/fixtures.ex
> +      |> List.to_string()
Yeah probably, I guess I got carried away :sweat_smile:

2021-04-20 00:21 UTC, ZeLarpMaster commented on lib/mobius/actions/utils.ex
> +        string_length = String.length(value)
Alright, thank you for trying that out :)

2021-04-20 00:25 UTC, ZeLarpMaster approved these changes
Good stuff! This will help with future actions too which is very nice :)

2021-04-20 00:25 UTC, merged